# Generated by Django 5.1.4 on 2024-12-26 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_imagedownload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.image')),
            ],
        ),
    ]
